export const mockProductListData = {
  products: [
    {
      id: "p1",
      name: "Smart Speaker Echo",
      imageUrl: "https://via.placeholder.com/300/4CAF50/ffffff?text=Echo+Speaker",
      price: 99.99,
      rating: 4.5,
      reviewCount: 150,
      href: "/products/p1",
    },
    {
      id: "p2",
      name: "Noise-Cancelling Headphones",
      imageUrl: "https://via.placeholder.com/300/2196F3/ffffff?text=Headphones",
      price: 199.99,
      rating: 4.8,
      reviewCount: 230,
      href: "/products/p2",
    },
    {
      id: "p3",
      name: "Portable SSD 1TB",
      imageUrl: "https://via.placeholder.com/300/FFC107/000000?text=SSD+1TB",
      price: 129.00,
      rating: 4.2,
      reviewCount: 85,
      href: "/products/p3",
    },
    {
      id: "p4",
      name: "Ergonomic Office Chair",
      imageUrl: "https://via.placeholder.com/300/9C27B0/ffffff?text=Office+Chair",
      price: 349.50,
      rating: 4.7,
      reviewCount: 190,
      href: "/products/p4",
    },
    {
      id: "p5",
      name: "4K UHD Monitor 27-inch",
      imageUrl: "https://via.placeholder.com/300/E91E63/ffffff?text=Monitor+4K",
      price: 299.00,
      rating: 4.6,
      reviewCount: 110,
      href: "/products/p5",
    },
    {
      id: "p6",
      name: "Gaming Mouse RGB",
      imageUrl: "https://via.placeholder.com/300/00BCD4/ffffff?text=Gaming+Mouse",
      price: 49.99,
      rating: 4.3,
      reviewCount: 200,
      href: "/products/p6",
    },
  ],
  sectionTitle: "Our Bestsellers",
};
